# Form implementation generated from reading ui file '.\ui_files\main_window_new_size.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1360, 875)
        MainWindow.setMinimumSize(QtCore.QSize(1360, 875))
        MainWindow.setMaximumSize(QtCore.QSize(1360, 875))
        MainWindow.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1360, 875))
        self.centralwidget.setMaximumSize(QtCore.QSize(1360, 875))
        self.centralwidget.setObjectName("centralwidget")
        self.algorithms_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.algorithms_frame.setGeometry(QtCore.QRect(1040, 180, 311, 191))
        self.algorithms_frame.setStyleSheet("QFrame\n"
"{\n"
"    border-radius: 10px;\n"
"    border: 3px solid rgb(80, 84, 90);\n"
"    background-color: rgb(210, 210, 210);\n"
"}")
        self.algorithms_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.algorithms_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.algorithms_frame.setObjectName("algorithms_frame")
        self.layoutWidget = QtWidgets.QWidget(parent=self.algorithms_frame)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 311, 191))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(15, 5, 0, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.canonical_button = QtWidgets.QRadioButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.canonical_button.setFont(font)
        self.canonical_button.setObjectName("canonical_button")
        self.verticalLayout.addWidget(self.canonical_button)
        self.paremetric_button = QtWidgets.QRadioButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.paremetric_button.setFont(font)
        self.paremetric_button.setObjectName("paremetric_button")
        self.verticalLayout.addWidget(self.paremetric_button)
        self.bresenham_button = QtWidgets.QRadioButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.bresenham_button.setFont(font)
        self.bresenham_button.setObjectName("bresenham_button")
        self.verticalLayout.addWidget(self.bresenham_button)
        self.midpoint_button = QtWidgets.QRadioButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.midpoint_button.setFont(font)
        self.midpoint_button.setObjectName("midpoint_button")
        self.verticalLayout.addWidget(self.midpoint_button)
        self.library_function_button = QtWidgets.QRadioButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.library_function_button.setFont(font)
        self.library_function_button.setObjectName("library_function_button")
        self.verticalLayout.addWidget(self.library_function_button)
        self.algorithms_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.algorithms_label.setGeometry(QtCore.QRect(1150, 150, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.algorithms_label.setFont(font)
        self.algorithms_label.setWhatsThis("")
        self.algorithms_label.setStyleSheet("QLabel\n"
"{\n"
"    color: rgb(112, 146, 190);\n"
"}")
        self.algorithms_label.setObjectName("algorithms_label")
        self.screen_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.screen_label.setGeometry(QtCore.QRect(1160, 0, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.screen_label.setFont(font)
        self.screen_label.setWhatsThis("")
        self.screen_label.setStyleSheet("QLabel\n"
"{\n"
"    color: rgb(112, 146, 190);\n"
"}")
        self.screen_label.setObjectName("screen_label")
        self.screen_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.screen_frame.setGeometry(QtCore.QRect(1040, 30, 311, 111))
        self.screen_frame.setStyleSheet("QFrame\n"
"{\n"
"    border-radius: 10px;\n"
"    border: 3px solid rgb(80, 84, 90);\n"
"    background-color: rgb(210, 210, 210);\n"
"}")
        self.screen_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.screen_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.screen_frame.setObjectName("screen_frame")
        self.screen_color_button = QtWidgets.QPushButton(parent=self.screen_frame)
        self.screen_color_button.setGeometry(QtCore.QRect(110, 10, 51, 31))
        self.screen_color_button.setStyleSheet("QPushButton\n"
"{\n"
"    border-radius: 4px;\n"
"    border: 2px solid rgb(110, 105, 100);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.screen_color_button.setText("")
        self.screen_color_button.setObjectName("screen_color_button")
        self.label_1 = QtWidgets.QLabel(parent=self.screen_frame)
        self.label_1.setGeometry(QtCore.QRect(20, 10, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.clear_screen_button = QtWidgets.QPushButton(parent=self.screen_frame)
        self.clear_screen_button.setGeometry(QtCore.QRect(20, 60, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.clear_screen_button.setFont(font)
        self.clear_screen_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(200, 82, 84);\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(140, 57, 60);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(140, 57, 60);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.clear_screen_button.setObjectName("clear_screen_button")
        self.label_16 = QtWidgets.QLabel(parent=self.screen_frame)
        self.label_16.setGeometry(QtCore.QRect(190, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(parent=self.screen_frame)
        self.label_17.setGeometry(QtCore.QRect(190, 60, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.circle_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.circle_label.setGeometry(QtCore.QRect(1140, 380, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.circle_label.setFont(font)
        self.circle_label.setWhatsThis("")
        self.circle_label.setStyleSheet("QLabel\n"
"{\n"
"    color: rgb(112, 146, 190);\n"
"}")
        self.circle_label.setObjectName("circle_label")
        self.circle_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.circle_frame.setGeometry(QtCore.QRect(1040, 410, 311, 271))
        self.circle_frame.setStyleSheet("QFrame\n"
"{\n"
"    border-radius: 10px;\n"
"    border: 3px solid rgb(80, 84, 90);\n"
"    background-color: rgb(210, 210, 210);\n"
"}")
        self.circle_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.circle_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.circle_frame.setObjectName("circle_frame")
        self.draw_circle_button = QtWidgets.QPushButton(parent=self.circle_frame)
        self.draw_circle_button.setGeometry(QtCore.QRect(10, 220, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.draw_circle_button.setFont(font)
        self.draw_circle_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(134, 226, 130);\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(65, 190, 55);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(65, 190, 55);\n"
"}\n"
"")
        self.draw_circle_button.setObjectName("draw_circle_button")
        self.label_9 = QtWidgets.QLabel(parent=self.circle_frame)
        self.label_9.setGeometry(QtCore.QRect(100, 70, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.circle_color_button = QtWidgets.QPushButton(parent=self.circle_frame)
        self.circle_color_button.setGeometry(QtCore.QRect(220, 10, 51, 31))
        self.circle_color_button.setStyleSheet("QPushButton\n"
"{\n"
"    border-radius: 4px;\n"
"    border: 2px solid rgb(110, 105, 100);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.circle_color_button.setText("")
        self.circle_color_button.setObjectName("circle_color_button")
        self.label_8 = QtWidgets.QLabel(parent=self.circle_frame)
        self.label_8.setGeometry(QtCore.QRect(100, 9, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.circle_mode_button = QtWidgets.QRadioButton(parent=self.circle_frame)
        self.circle_mode_button.setGeometry(QtCore.QRect(10, 30, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.circle_mode_button.setFont(font)
        self.circle_mode_button.setObjectName("circle_mode_button")
        self.ellipse_mode_button = QtWidgets.QRadioButton(parent=self.circle_frame)
        self.ellipse_mode_button.setGeometry(QtCore.QRect(10, 60, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.ellipse_mode_button.setFont(font)
        self.ellipse_mode_button.setObjectName("ellipse_mode_button")
        self.circle_center_x_field = QtWidgets.QLineEdit(parent=self.circle_frame)
        self.circle_center_x_field.setGeometry(QtCore.QRect(40, 100, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.circle_center_x_field.setFont(font)
        self.circle_center_x_field.setStyleSheet("QLineEdit\n"
"{\n"
"    border-radius: 5px;\n"
"}")
        self.circle_center_x_field.setObjectName("circle_center_x_field")
        self.circle_center_y_field = QtWidgets.QLineEdit(parent=self.circle_frame)
        self.circle_center_y_field.setGeometry(QtCore.QRect(40, 130, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.circle_center_y_field.setFont(font)
        self.circle_center_y_field.setStyleSheet("QLineEdit\n"
"{\n"
"    border-radius: 5px;\n"
"}")
        self.circle_center_y_field.setObjectName("circle_center_y_field")
        self.circle_raduis_field = QtWidgets.QLineEdit(parent=self.circle_frame)
        self.circle_raduis_field.setGeometry(QtCore.QRect(40, 190, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.circle_raduis_field.setFont(font)
        self.circle_raduis_field.setStyleSheet("QLineEdit\n"
"{\n"
"    border-radius: 5px;\n"
"}")
        self.circle_raduis_field.setObjectName("circle_raduis_field")
        self.label_12 = QtWidgets.QLabel(parent=self.circle_frame)
        self.label_12.setGeometry(QtCore.QRect(100, 160, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.specter_check_box = QtWidgets.QCheckBox(parent=self.circle_frame)
        self.specter_check_box.setGeometry(QtCore.QRect(10, 0, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.specter_check_box.setFont(font)
        self.specter_check_box.setObjectName("specter_check_box")
        self.label_13 = QtWidgets.QLabel(parent=self.circle_frame)
        self.label_13.setGeometry(QtCore.QRect(10, 180, 21, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_10 = QtWidgets.QLabel(parent=self.circle_frame)
        self.label_10.setGeometry(QtCore.QRect(10, 90, 21, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.circle_frame)
        self.label_11.setGeometry(QtCore.QRect(10, 120, 21, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.ellipse_frame = QtWidgets.QFrame(parent=self.circle_frame)
        self.ellipse_frame.setGeometry(QtCore.QRect(0, 0, 311, 291))
        self.ellipse_frame.setStyleSheet("QFrame\n"
"{\n"
"    border-radius: 10px;\n"
"    border: 3px solid rgb(80, 84, 90);\n"
"    background-color: rgb(210, 210, 210);\n"
"}")
        self.ellipse_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.ellipse_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ellipse_frame.setObjectName("ellipse_frame")
        self.draw_ellipse_button = QtWidgets.QPushButton(parent=self.ellipse_frame)
        self.draw_ellipse_button.setGeometry(QtCore.QRect(10, 240, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.draw_ellipse_button.setFont(font)
        self.draw_ellipse_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(134, 226, 130);\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(65, 190, 55);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(65, 190, 55);\n"
"}\n"
"")
        self.draw_ellipse_button.setObjectName("draw_ellipse_button")
        self.label_5 = QtWidgets.QLabel(parent=self.ellipse_frame)
        self.label_5.setGeometry(QtCore.QRect(6, 120, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(parent=self.ellipse_frame)
        self.label_4.setGeometry(QtCore.QRect(6, 90, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(parent=self.ellipse_frame)
        self.label_3.setGeometry(QtCore.QRect(100, 50, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(parent=self.ellipse_frame)
        self.label_7.setGeometry(QtCore.QRect(6, 180, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.ellipse_color_button = QtWidgets.QPushButton(parent=self.ellipse_frame)
        self.ellipse_color_button.setGeometry(QtCore.QRect(200, 10, 51, 31))
        self.ellipse_color_button.setStyleSheet("QPushButton\n"
"{\n"
"    border-radius: 4px;\n"
"    border: 2px solid rgb(110, 105, 100);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.ellipse_color_button.setText("")
        self.ellipse_color_button.setObjectName("ellipse_color_button")
        self.label_2 = QtWidgets.QLabel(parent=self.ellipse_frame)
        self.label_2.setGeometry(QtCore.QRect(100, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.ellipse_center_x_field = QtWidgets.QLineEdit(parent=self.ellipse_frame)
        self.ellipse_center_x_field.setGeometry(QtCore.QRect(40, 90, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.ellipse_center_x_field.setFont(font)
        self.ellipse_center_x_field.setStyleSheet("QLineEdit\n"
"{\n"
"    border-radius: 5px;\n"
"}")
        self.ellipse_center_x_field.setObjectName("ellipse_center_x_field")
        self.ellipse_center_y_field = QtWidgets.QLineEdit(parent=self.ellipse_frame)
        self.ellipse_center_y_field.setGeometry(QtCore.QRect(40, 120, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.ellipse_center_y_field.setFont(font)
        self.ellipse_center_y_field.setStyleSheet("QLineEdit\n"
"{\n"
"    border-radius: 5px;\n"
"}")
        self.ellipse_center_y_field.setObjectName("ellipse_center_y_field")
        self.ellipse_radius_x_field = QtWidgets.QLineEdit(parent=self.ellipse_frame)
        self.ellipse_radius_x_field.setGeometry(QtCore.QRect(40, 180, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.ellipse_radius_x_field.setFont(font)
        self.ellipse_radius_x_field.setStyleSheet("QLineEdit\n"
"{\n"
"    border-radius: 5px;\n"
"}")
        self.ellipse_radius_x_field.setObjectName("ellipse_radius_x_field")
        self.label_6 = QtWidgets.QLabel(parent=self.ellipse_frame)
        self.label_6.setGeometry(QtCore.QRect(100, 150, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_15 = QtWidgets.QLabel(parent=self.ellipse_frame)
        self.label_15.setGeometry(QtCore.QRect(6, 210, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.ellipse_radius_y_field = QtWidgets.QLineEdit(parent=self.ellipse_frame)
        self.ellipse_radius_y_field.setGeometry(QtCore.QRect(40, 210, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.ellipse_radius_y_field.setFont(font)
        self.ellipse_radius_y_field.setStyleSheet("QLineEdit\n"
"{\n"
"    border-radius: 5px;\n"
"}")
        self.ellipse_radius_y_field.setObjectName("ellipse_radius_y_field")
        self.circle_specter_frame = QtWidgets.QFrame(parent=self.ellipse_frame)
        self.circle_specter_frame.setGeometry(QtCore.QRect(0, 0, 311, 361))
        self.circle_specter_frame.setStyleSheet("QFrame\n"
"{\n"
"    border-radius: 10px;\n"
"    border: 3px solid rgb(80, 84, 90);\n"
"    background-color: rgb(210, 210, 210);\n"
"}")
        self.circle_specter_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.circle_specter_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.circle_specter_frame.setObjectName("circle_specter_frame")
        self.draw_circle_specter_button = QtWidgets.QPushButton(parent=self.circle_specter_frame)
        self.draw_circle_specter_button.setGeometry(QtCore.QRect(10, 310, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.draw_circle_specter_button.setFont(font)
        self.draw_circle_specter_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(134, 226, 130);\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(65, 190, 55);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(65, 190, 55);\n"
"}\n"
"")
        self.draw_circle_specter_button.setObjectName("draw_circle_specter_button")
        self.label_26 = QtWidgets.QLabel(parent=self.circle_specter_frame)
        self.label_26.setGeometry(QtCore.QRect(100, 70, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.circle_specter_color_button = QtWidgets.QPushButton(parent=self.circle_specter_frame)
        self.circle_specter_color_button.setGeometry(QtCore.QRect(220, 10, 51, 31))
        self.circle_specter_color_button.setStyleSheet("QPushButton\n"
"{\n"
"    border-radius: 4px;\n"
"    border: 2px solid rgb(110, 105, 100);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.circle_specter_color_button.setText("")
        self.circle_specter_color_button.setObjectName("circle_specter_color_button")
        self.label_37 = QtWidgets.QLabel(parent=self.circle_specter_frame)
        self.label_37.setGeometry(QtCore.QRect(100, 9, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.circle_specter_center_x_field = QtWidgets.QLineEdit(parent=self.circle_specter_frame)
        self.circle_specter_center_x_field.setGeometry(QtCore.QRect(40, 100, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.circle_specter_center_x_field.setFont(font)
        self.circle_specter_center_x_field.setStyleSheet("QLineEdit\n"
"{\n"
"    border-radius: 5px;\n"
"}")
        self.circle_specter_center_x_field.setObjectName("circle_specter_center_x_field")
        self.circle_specter_center_y_field = QtWidgets.QLineEdit(parent=self.circle_specter_frame)
        self.circle_specter_center_y_field.setGeometry(QtCore.QRect(40, 130, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.circle_specter_center_y_field.setFont(font)
        self.circle_specter_center_y_field.setStyleSheet("QLineEdit\n"
"{\n"
"    border-radius: 5px;\n"
"}")
        self.circle_specter_center_y_field.setObjectName("circle_specter_center_y_field")
        self.circle_specter_raduis_field = QtWidgets.QLineEdit(parent=self.circle_specter_frame)
        self.circle_specter_raduis_field.setGeometry(QtCore.QRect(40, 190, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.circle_specter_raduis_field.setFont(font)
        self.circle_specter_raduis_field.setStyleSheet("QLineEdit\n"
"{\n"
"    border-radius: 5px;\n"
"}")
        self.circle_specter_raduis_field.setObjectName("circle_specter_raduis_field")
        self.label_38 = QtWidgets.QLabel(parent=self.circle_specter_frame)
        self.label_38.setGeometry(QtCore.QRect(100, 160, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(parent=self.circle_specter_frame)
        self.label_39.setGeometry(QtCore.QRect(11, 180, 21, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.circle_specter_step_field = QtWidgets.QLineEdit(parent=self.circle_specter_frame)
        self.circle_specter_step_field.setGeometry(QtCore.QRect(70, 250, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.circle_specter_step_field.setFont(font)
        self.circle_specter_step_field.setStyleSheet("QLineEdit\n"
"{\n"
"    border-radius: 5px;\n"
"}")
        self.circle_specter_step_field.setObjectName("circle_specter_step_field")
        self.label_40 = QtWidgets.QLabel(parent=self.circle_specter_frame)
        self.label_40.setGeometry(QtCore.QRect(100, 220, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(parent=self.circle_specter_frame)
        self.label_41.setGeometry(QtCore.QRect(6, 280, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.circle_specters_count_field = QtWidgets.QLineEdit(parent=self.circle_specter_frame)
        self.circle_specters_count_field.setGeometry(QtCore.QRect(70, 280, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.circle_specters_count_field.setFont(font)
        self.circle_specters_count_field.setStyleSheet("QLineEdit\n"
"{\n"
"    border-radius: 5px;\n"
"}")
        self.circle_specters_count_field.setObjectName("circle_specters_count_field")
        self.label_42 = QtWidgets.QLabel(parent=self.circle_specter_frame)
        self.label_42.setGeometry(QtCore.QRect(16, 250, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(parent=self.circle_specter_frame)
        self.label_43.setGeometry(QtCore.QRect(10, 90, 21, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(parent=self.circle_specter_frame)
        self.label_44.setGeometry(QtCore.QRect(10, 120, 21, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.ellipse_specter_frame = QtWidgets.QFrame(parent=self.circle_specter_frame)
        self.ellipse_specter_frame.setGeometry(QtCore.QRect(0, 0, 311, 381))
        self.ellipse_specter_frame.setStyleSheet("QFrame\n"
"{\n"
"    border-radius: 10px;\n"
"    border: 3px solid rgb(80, 84, 90);\n"
"    background-color: rgb(210, 210, 210);\n"
"}")
        self.ellipse_specter_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.ellipse_specter_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ellipse_specter_frame.setObjectName("ellipse_specter_frame")
        self.draw_ellipse_specter_button = QtWidgets.QPushButton(parent=self.ellipse_specter_frame)
        self.draw_ellipse_specter_button.setGeometry(QtCore.QRect(10, 330, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.draw_ellipse_specter_button.setFont(font)
        self.draw_ellipse_specter_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(134, 226, 130);\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(65, 190, 55);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(65, 190, 55);\n"
"}\n"
"")
        self.draw_ellipse_specter_button.setObjectName("draw_ellipse_specter_button")
        self.label_24 = QtWidgets.QLabel(parent=self.ellipse_specter_frame)
        self.label_24.setGeometry(QtCore.QRect(6, 120, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(parent=self.ellipse_specter_frame)
        self.label_25.setGeometry(QtCore.QRect(6, 90, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_29 = QtWidgets.QLabel(parent=self.ellipse_specter_frame)
        self.label_29.setGeometry(QtCore.QRect(100, 50, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(parent=self.ellipse_specter_frame)
        self.label_30.setGeometry(QtCore.QRect(6, 180, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.ellipse_specter_color_button = QtWidgets.QPushButton(parent=self.ellipse_specter_frame)
        self.ellipse_specter_color_button.setGeometry(QtCore.QRect(200, 10, 51, 31))
        self.ellipse_specter_color_button.setStyleSheet("QPushButton\n"
"{\n"
"    border-radius: 4px;\n"
"    border: 2px solid rgb(110, 105, 100);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.ellipse_specter_color_button.setText("")
        self.ellipse_specter_color_button.setObjectName("ellipse_specter_color_button")
        self.label_31 = QtWidgets.QLabel(parent=self.ellipse_specter_frame)
        self.label_31.setGeometry(QtCore.QRect(100, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.ellipse_specter_center_x_field = QtWidgets.QLineEdit(parent=self.ellipse_specter_frame)
        self.ellipse_specter_center_x_field.setGeometry(QtCore.QRect(40, 90, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.ellipse_specter_center_x_field.setFont(font)
        self.ellipse_specter_center_x_field.setStyleSheet("QLineEdit\n"
"{\n"
"    border-radius: 5px;\n"
"}")
        self.ellipse_specter_center_x_field.setObjectName("ellipse_specter_center_x_field")
        self.ellipse_specter_center_y_field = QtWidgets.QLineEdit(parent=self.ellipse_specter_frame)
        self.ellipse_specter_center_y_field.setGeometry(QtCore.QRect(40, 120, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.ellipse_specter_center_y_field.setFont(font)
        self.ellipse_specter_center_y_field.setStyleSheet("QLineEdit\n"
"{\n"
"    border-radius: 5px;\n"
"}")
        self.ellipse_specter_center_y_field.setObjectName("ellipse_specter_center_y_field")
        self.ellipse_specter_radius_x_field = QtWidgets.QLineEdit(parent=self.ellipse_specter_frame)
        self.ellipse_specter_radius_x_field.setGeometry(QtCore.QRect(40, 180, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.ellipse_specter_radius_x_field.setFont(font)
        self.ellipse_specter_radius_x_field.setStyleSheet("QLineEdit\n"
"{\n"
"    border-radius: 5px;\n"
"}")
        self.ellipse_specter_radius_x_field.setObjectName("ellipse_specter_radius_x_field")
        self.label_32 = QtWidgets.QLabel(parent=self.ellipse_specter_frame)
        self.label_32.setGeometry(QtCore.QRect(100, 150, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(parent=self.ellipse_specter_frame)
        self.label_33.setGeometry(QtCore.QRect(6, 210, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.ellipse_specter_radius_y_field = QtWidgets.QLineEdit(parent=self.ellipse_specter_frame)
        self.ellipse_specter_radius_y_field.setGeometry(QtCore.QRect(40, 210, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.ellipse_specter_radius_y_field.setFont(font)
        self.ellipse_specter_radius_y_field.setStyleSheet("QLineEdit\n"
"{\n"
"    border-radius: 5px;\n"
"}")
        self.ellipse_specter_radius_y_field.setObjectName("ellipse_specter_radius_y_field")
        self.ellipse_specters_count_field = QtWidgets.QLineEdit(parent=self.ellipse_specter_frame)
        self.ellipse_specters_count_field.setGeometry(QtCore.QRect(70, 300, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.ellipse_specters_count_field.setFont(font)
        self.ellipse_specters_count_field.setStyleSheet("QLineEdit\n"
"{\n"
"    border-radius: 5px;\n"
"}")
        self.ellipse_specters_count_field.setObjectName("ellipse_specters_count_field")
        self.ellipse_specter_step_field = QtWidgets.QLineEdit(parent=self.ellipse_specter_frame)
        self.ellipse_specter_step_field.setGeometry(QtCore.QRect(70, 270, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.ellipse_specter_step_field.setFont(font)
        self.ellipse_specter_step_field.setStyleSheet("QLineEdit\n"
"{\n"
"    border-radius: 5px;\n"
"}")
        self.ellipse_specter_step_field.setObjectName("ellipse_specter_step_field")
        self.label_34 = QtWidgets.QLabel(parent=self.ellipse_specter_frame)
        self.label_34.setGeometry(QtCore.QRect(6, 300, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(parent=self.ellipse_specter_frame)
        self.label_35.setGeometry(QtCore.QRect(16, 270, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(parent=self.ellipse_specter_frame)
        self.label_36.setGeometry(QtCore.QRect(100, 240, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.measurements_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.measurements_frame.setGeometry(QtCore.QRect(1040, 800, 311, 61))
        self.measurements_frame.setStyleSheet("QFrame\n"
"{\n"
"    border-radius: 10px;\n"
"    border: 3px solid rgb(80, 84, 90);\n"
"    background-color: rgb(210, 210, 210);\n"
"}")
        self.measurements_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.measurements_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.measurements_frame.setObjectName("measurements_frame")
        self.time_measurement_circle_button = QtWidgets.QPushButton(parent=self.measurements_frame)
        self.time_measurement_circle_button.setGeometry(QtCore.QRect(10, 10, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.time_measurement_circle_button.setFont(font)
        self.time_measurement_circle_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(146, 164, 175);\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(115, 138, 153);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(115, 138, 153);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.time_measurement_circle_button.setObjectName("time_measurement_circle_button")
        self.time_measurement_ellipse_button = QtWidgets.QPushButton(parent=self.measurements_frame)
        self.time_measurement_ellipse_button.setGeometry(QtCore.QRect(10, 10, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.time_measurement_ellipse_button.setFont(font)
        self.time_measurement_ellipse_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(146, 164, 175);\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(115, 138, 153);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(115, 138, 153);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.time_measurement_ellipse_button.setObjectName("time_measurement_ellipse_button")
        self.ellipse_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.ellipse_label.setGeometry(QtCore.QRect(1140, 380, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ellipse_label.setFont(font)
        self.ellipse_label.setWhatsThis("")
        self.ellipse_label.setStyleSheet("QLabel\n"
"{\n"
"    color: rgb(112, 146, 190);\n"
"}")
        self.ellipse_label.setObjectName("ellipse_label")
        self.pixmap_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.pixmap_label.setEnabled(True)
        self.pixmap_label.setGeometry(QtCore.QRect(20, 19, 1000, 840))
        self.pixmap_label.setMinimumSize(QtCore.QSize(900, 500))
        self.pixmap_label.setMaximumSize(QtCore.QSize(1800, 1350))
        self.pixmap_label.setStyleSheet("")
        self.pixmap_label.setText("")
        self.pixmap_label.setObjectName("pixmap_label")
        self.circle_specter_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.circle_specter_label.setGeometry(QtCore.QRect(1110, 380, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.circle_specter_label.setFont(font)
        self.circle_specter_label.setWhatsThis("")
        self.circle_specter_label.setStyleSheet("QLabel\n"
"{\n"
"    color: rgb(112, 146, 190);\n"
"}")
        self.circle_specter_label.setObjectName("circle_specter_label")
        self.ellipse_specter_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.ellipse_specter_label.setGeometry(QtCore.QRect(1120, 380, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ellipse_specter_label.setFont(font)
        self.ellipse_specter_label.setWhatsThis("")
        self.ellipse_specter_label.setStyleSheet("QLabel\n"
"{\n"
"    color: rgb(112, 146, 190);\n"
"}")
        self.ellipse_specter_label.setObjectName("ellipse_specter_label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "computer graphic lab_04"))
        self.canonical_button.setText(_translate("MainWindow", "Каноническое уравнение"))
        self.paremetric_button.setText(_translate("MainWindow", "Параметрическое уравнение"))
        self.bresenham_button.setText(_translate("MainWindow", "Алгоритм Брезенхема"))
        self.midpoint_button.setText(_translate("MainWindow", "Алгоритм средней точки"))
        self.library_function_button.setText(_translate("MainWindow", "Библиотечная функция"))
        self.algorithms_label.setText(_translate("MainWindow", "Алгоритм"))
        self.screen_label.setText(_translate("MainWindow", "Экран"))
        self.label_1.setText(_translate("MainWindow", "Цвет фона"))
        self.clear_screen_button.setText(_translate("MainWindow", "Очистить экран"))
        self.label_16.setText(_translate("MainWindow", "Размер экрана:"))
        self.label_17.setText(_translate("MainWindow", "1000 x 840"))
        self.circle_label.setText(_translate("MainWindow", "Окружность"))
        self.draw_circle_button.setText(_translate("MainWindow", "Построить окружность"))
        self.label_9.setText(_translate("MainWindow", "Центр окружности"))
        self.label_8.setText(_translate("MainWindow", "Цвет окружности"))
        self.circle_mode_button.setText(_translate("MainWindow", "Окружность"))
        self.ellipse_mode_button.setText(_translate("MainWindow", "Эллипс"))
        self.label_12.setText(_translate("MainWindow", "Радиус окружности"))
        self.specter_check_box.setText(_translate("MainWindow", "Cпектр"))
        self.label_13.setText(_translate("MainWindow", "R:"))
        self.label_10.setText(_translate("MainWindow", "X:"))
        self.label_11.setText(_translate("MainWindow", "Y:"))
        self.draw_ellipse_button.setText(_translate("MainWindow", "Построить эллипс"))
        self.label_5.setText(_translate("MainWindow", "Y:"))
        self.label_4.setText(_translate("MainWindow", "X:"))
        self.label_3.setText(_translate("MainWindow", "Центр эллипса"))
        self.label_7.setText(_translate("MainWindow", "Rx:"))
        self.label_2.setText(_translate("MainWindow", "Цвет эллипса"))
        self.label_6.setText(_translate("MainWindow", "Радиусы эллипса"))
        self.label_15.setText(_translate("MainWindow", "Ry:"))
        self.draw_circle_specter_button.setText(_translate("MainWindow", "Построить спектр окружностей"))
        self.label_26.setText(_translate("MainWindow", "Центр окружности"))
        self.label_37.setText(_translate("MainWindow", "Цвет окружности"))
        self.label_38.setText(_translate("MainWindow", "Радиус окружности"))
        self.label_39.setText(_translate("MainWindow", "R:"))
        self.label_40.setText(_translate("MainWindow", "Параметры спектра"))
        self.label_41.setText(_translate("MainWindow", "Кол-во:"))
        self.label_42.setText(_translate("MainWindow", "Шаг:"))
        self.label_43.setText(_translate("MainWindow", "X:"))
        self.label_44.setText(_translate("MainWindow", "Y:"))
        self.draw_ellipse_specter_button.setText(_translate("MainWindow", "Построить спектр эллипсов"))
        self.label_24.setText(_translate("MainWindow", "Y:"))
        self.label_25.setText(_translate("MainWindow", "X:"))
        self.label_29.setText(_translate("MainWindow", "Центр эллипса"))
        self.label_30.setText(_translate("MainWindow", "Rx:"))
        self.label_31.setText(_translate("MainWindow", "Цвет эллипса"))
        self.label_32.setText(_translate("MainWindow", "Радиусы эллипса"))
        self.label_33.setText(_translate("MainWindow", "Ry:"))
        self.label_34.setText(_translate("MainWindow", "Кол-во:"))
        self.label_35.setText(_translate("MainWindow", "Шаг:"))
        self.label_36.setText(_translate("MainWindow", "Параметры спектра"))
        self.time_measurement_circle_button.setText(_translate("MainWindow", "Замеры времени для окружностей"))
        self.time_measurement_ellipse_button.setText(_translate("MainWindow", "Замеры времени для эллипсов"))
        self.ellipse_label.setText(_translate("MainWindow", "Элипс"))
        self.circle_specter_label.setText(_translate("MainWindow", "Спектр окружностей"))
        self.ellipse_specter_label.setText(_translate("MainWindow", "Спектр эллипсов"))
