# Form implementation generated from reading ui file 'ui_files\main_window.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2480, 1390)
        MainWindow.setMinimumSize(QtCore.QSize(2480, 1390))
        MainWindow.setMaximumSize(QtCore.QSize(2480, 1391))
        MainWindow.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(2480, 1380))
        self.centralwidget.setObjectName("centralwidget")
        self.algorithms_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.algorithms_frame.setGeometry(QtCore.QRect(1850, 260, 611, 371))
        self.algorithms_frame.setStyleSheet("QFrame\n"
"{\n"
"    border-radius: 10px;\n"
"    border: 3px solid rgb(80, 84, 90);\n"
"    background-color: rgb(210, 210, 210);\n"
"}")
        self.algorithms_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.algorithms_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.algorithms_frame.setObjectName("algorithms_frame")
        self.layoutWidget = QtWidgets.QWidget(parent=self.algorithms_frame)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 611, 371))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(15, 5, 0, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cda_button = QtWidgets.QRadioButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.cda_button.setFont(font)
        self.cda_button.setObjectName("cda_button")
        self.verticalLayout.addWidget(self.cda_button)
        self.bresenham_float_button = QtWidgets.QRadioButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.bresenham_float_button.setFont(font)
        self.bresenham_float_button.setObjectName("bresenham_float_button")
        self.verticalLayout.addWidget(self.bresenham_float_button)
        self.bresenham_int_button = QtWidgets.QRadioButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.bresenham_int_button.setFont(font)
        self.bresenham_int_button.setObjectName("bresenham_int_button")
        self.verticalLayout.addWidget(self.bresenham_int_button)
        self.bresenham_without_gradation_button = QtWidgets.QRadioButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.bresenham_without_gradation_button.setFont(font)
        self.bresenham_without_gradation_button.setObjectName("bresenham_without_gradation_button")
        self.verticalLayout.addWidget(self.bresenham_without_gradation_button)
        self.vu_button = QtWidgets.QRadioButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.vu_button.setFont(font)
        self.vu_button.setObjectName("vu_button")
        self.verticalLayout.addWidget(self.vu_button)
        self.library_function_button = QtWidgets.QRadioButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.library_function_button.setFont(font)
        self.library_function_button.setObjectName("library_function_button")
        self.verticalLayout.addWidget(self.library_function_button)
        self.measurements_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.measurements_frame.setGeometry(QtCore.QRect(1850, 1190, 611, 181))
        self.measurements_frame.setStyleSheet("QFrame\n"
"{\n"
"    border-radius: 10px;\n"
"    border: 3px solid rgb(80, 84, 90);\n"
"    background-color: rgb(210, 210, 210);\n"
"}")
        self.measurements_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.measurements_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.measurements_frame.setObjectName("measurements_frame")
        self.gradation_measurement_button = QtWidgets.QPushButton(parent=self.measurements_frame)
        self.gradation_measurement_button.setGeometry(QtCore.QRect(20, 20, 571, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.gradation_measurement_button.setFont(font)
        self.gradation_measurement_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(146, 164, 175);\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(115, 138, 153);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(115, 138, 153);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.gradation_measurement_button.setObjectName("gradation_measurement_button")
        self.time_measurement_button = QtWidgets.QPushButton(parent=self.measurements_frame)
        self.time_measurement_button.setGeometry(QtCore.QRect(20, 100, 571, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.time_measurement_button.setFont(font)
        self.time_measurement_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(146, 164, 175);\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(115, 138, 153);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(115, 138, 153);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.time_measurement_button.setObjectName("time_measurement_button")
        self.algorithms_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.algorithms_label.setGeometry(QtCore.QRect(2070, 190, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.algorithms_label.setFont(font)
        self.algorithms_label.setWhatsThis("")
        self.algorithms_label.setStyleSheet("QLabel\n"
"{\n"
"    color: rgb(112, 146, 190);\n"
"}")
        self.algorithms_label.setObjectName("algorithms_label")
        self.line_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.line_label.setGeometry(QtCore.QRect(2080, 630, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.line_label.setFont(font)
        self.line_label.setWhatsThis("")
        self.line_label.setStyleSheet("QLabel\n"
"{\n"
"    color: rgb(112, 146, 190);\n"
"}")
        self.line_label.setObjectName("line_label")
        self.measurements_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.measurements_label.setGeometry(QtCore.QRect(2090, 1120, 341, 71))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.measurements_label.setFont(font)
        self.measurements_label.setWhatsThis("")
        self.measurements_label.setStyleSheet("QLabel\n"
"{\n"
"    color: rgb(112, 146, 190);\n"
"}")
        self.measurements_label.setObjectName("measurements_label")
        self.screen_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.screen_label.setGeometry(QtCore.QRect(2100, -10, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.screen_label.setFont(font)
        self.screen_label.setWhatsThis("")
        self.screen_label.setStyleSheet("QLabel\n"
"{\n"
"    color: rgb(112, 146, 190);\n"
"}")
        self.screen_label.setObjectName("screen_label")
        self.screen_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.screen_frame.setGeometry(QtCore.QRect(1850, 50, 611, 141))
        self.screen_frame.setStyleSheet("QFrame\n"
"{\n"
"    border-radius: 10px;\n"
"    border: 3px solid rgb(80, 84, 90);\n"
"    background-color: rgb(210, 210, 210);\n"
"}")
        self.screen_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.screen_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.screen_frame.setObjectName("screen_frame")
        self.screen_color_button = QtWidgets.QPushButton(parent=self.screen_frame)
        self.screen_color_button.setGeometry(QtCore.QRect(180, 10, 81, 41))
        self.screen_color_button.setStyleSheet("QPushButton\n"
"{\n"
"    border-radius: 4px;\n"
"    border: 2px solid rgb(110, 105, 100);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.screen_color_button.setText("")
        self.screen_color_button.setObjectName("screen_color_button")
        self.label_1 = QtWidgets.QLabel(parent=self.screen_frame)
        self.label_1.setGeometry(QtCore.QRect(30, 10, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.clear_screen_button = QtWidgets.QPushButton(parent=self.screen_frame)
        self.clear_screen_button.setGeometry(QtCore.QRect(30, 60, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.clear_screen_button.setFont(font)
        self.clear_screen_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(200, 82, 84);\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(140, 57, 60);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(140, 57, 60);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.clear_screen_button.setObjectName("clear_screen_button")
        self.label_16 = QtWidgets.QLabel(parent=self.screen_frame)
        self.label_16.setGeometry(QtCore.QRect(310, 10, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(parent=self.screen_frame)
        self.label_17.setGeometry(QtCore.QRect(310, 60, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.line_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_frame.setGeometry(QtCore.QRect(1850, 700, 611, 421))
        self.line_frame.setStyleSheet("QFrame\n"
"{\n"
"    border-radius: 10px;\n"
"    border: 3px solid rgb(80, 84, 90);\n"
"    background-color: rgb(210, 210, 210);\n"
"}")
        self.line_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.line_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.line_frame.setObjectName("line_frame")
        self.draw_line_button = QtWidgets.QPushButton(parent=self.line_frame)
        self.draw_line_button.setGeometry(QtCore.QRect(10, 340, 591, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.draw_line_button.setFont(font)
        self.draw_line_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(134, 226, 130);\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(65, 190, 55);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(65, 190, 55);\n"
"}\n"
"")
        self.draw_line_button.setObjectName("draw_line_button")
        self.label_11 = QtWidgets.QLabel(parent=self.line_frame)
        self.label_11.setGeometry(QtCore.QRect(16, 180, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_10 = QtWidgets.QLabel(parent=self.line_frame)
        self.label_10.setGeometry(QtCore.QRect(16, 140, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_9 = QtWidgets.QLabel(parent=self.line_frame)
        self.label_9.setGeometry(QtCore.QRect(220, 100, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_14 = QtWidgets.QLabel(parent=self.line_frame)
        self.label_14.setGeometry(QtCore.QRect(16, 300, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_13 = QtWidgets.QLabel(parent=self.line_frame)
        self.label_13.setGeometry(QtCore.QRect(16, 260, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.line_color_button = QtWidgets.QPushButton(parent=self.line_frame)
        self.line_color_button.setGeometry(QtCore.QRect(410, 30, 81, 41))
        self.line_color_button.setStyleSheet("QPushButton\n"
"{\n"
"    border-radius: 4px;\n"
"    border: 2px solid rgb(110, 105, 100);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.line_color_button.setText("")
        self.line_color_button.setObjectName("line_color_button")
        self.label_8 = QtWidgets.QLabel(parent=self.line_frame)
        self.label_8.setGeometry(QtCore.QRect(220, 30, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.line_mode_button = QtWidgets.QRadioButton(parent=self.line_frame)
        self.line_mode_button.setGeometry(QtCore.QRect(20, 30, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.line_mode_button.setFont(font)
        self.line_mode_button.setObjectName("line_mode_button")
        self.specter_mode_button = QtWidgets.QRadioButton(parent=self.line_frame)
        self.specter_mode_button.setGeometry(QtCore.QRect(20, 80, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.specter_mode_button.setFont(font)
        self.specter_mode_button.setObjectName("specter_mode_button")
        self.line_start_x_field = QtWidgets.QLineEdit(parent=self.line_frame)
        self.line_start_x_field.setGeometry(QtCore.QRect(50, 140, 551, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.line_start_x_field.setFont(font)
        self.line_start_x_field.setStyleSheet("QLineEdit\n"
"{\n"
"    border-radius: 5px;\n"
"}")
        self.line_start_x_field.setObjectName("line_start_x_field")
        self.line_start_y_field = QtWidgets.QLineEdit(parent=self.line_frame)
        self.line_start_y_field.setGeometry(QtCore.QRect(50, 180, 551, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.line_start_y_field.setFont(font)
        self.line_start_y_field.setStyleSheet("QLineEdit\n"
"{\n"
"    border-radius: 5px;\n"
"}")
        self.line_start_y_field.setObjectName("line_start_y_field")
        self.line_end_x_field = QtWidgets.QLineEdit(parent=self.line_frame)
        self.line_end_x_field.setGeometry(QtCore.QRect(50, 260, 551, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.line_end_x_field.setFont(font)
        self.line_end_x_field.setStyleSheet("QLineEdit\n"
"{\n"
"    border-radius: 5px;\n"
"}")
        self.line_end_x_field.setObjectName("line_end_x_field")
        self.line_end_y_field = QtWidgets.QLineEdit(parent=self.line_frame)
        self.line_end_y_field.setGeometry(QtCore.QRect(50, 300, 551, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.line_end_y_field.setFont(font)
        self.line_end_y_field.setStyleSheet("QLineEdit\n"
"{\n"
"    border-radius: 5px;\n"
"}")
        self.line_end_y_field.setObjectName("line_end_y_field")
        self.label_12 = QtWidgets.QLabel(parent=self.line_frame)
        self.label_12.setGeometry(QtCore.QRect(220, 220, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.specter_frame = QtWidgets.QFrame(parent=self.line_frame)
        self.specter_frame.setGeometry(QtCore.QRect(0, 0, 611, 421))
        self.specter_frame.setStyleSheet("QFrame\n"
"{\n"
"    border-radius: 10px;\n"
"    border: 3px solid rgb(80, 84, 90);\n"
"    background-color: rgb(210, 210, 210);\n"
"}")
        self.specter_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.specter_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.specter_frame.setObjectName("specter_frame")
        self.draw_specter_button = QtWidgets.QPushButton(parent=self.specter_frame)
        self.draw_specter_button.setGeometry(QtCore.QRect(10, 340, 591, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.draw_specter_button.setFont(font)
        self.draw_specter_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(134, 226, 130);\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(65, 190, 55);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(65, 190, 55);\n"
"}\n"
"")
        self.draw_specter_button.setObjectName("draw_specter_button")
        self.label_5 = QtWidgets.QLabel(parent=self.specter_frame)
        self.label_5.setGeometry(QtCore.QRect(16, 180, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(parent=self.specter_frame)
        self.label_4.setGeometry(QtCore.QRect(16, 140, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(parent=self.specter_frame)
        self.label_3.setGeometry(QtCore.QRect(220, 100, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(parent=self.specter_frame)
        self.label_7.setGeometry(QtCore.QRect(16, 260, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.specter_color_button = QtWidgets.QPushButton(parent=self.specter_frame)
        self.specter_color_button.setGeometry(QtCore.QRect(410, 30, 81, 41))
        self.specter_color_button.setStyleSheet("QPushButton\n"
"{\n"
"    border-radius: 4px;\n"
"    border: 2px solid rgb(110, 105, 100);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.specter_color_button.setText("")
        self.specter_color_button.setObjectName("specter_color_button")
        self.label_2 = QtWidgets.QLabel(parent=self.specter_frame)
        self.label_2.setGeometry(QtCore.QRect(220, 30, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.specter_center_x_field = QtWidgets.QLineEdit(parent=self.specter_frame)
        self.specter_center_x_field.setGeometry(QtCore.QRect(50, 140, 551, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.specter_center_x_field.setFont(font)
        self.specter_center_x_field.setStyleSheet("QLineEdit\n"
"{\n"
"    border-radius: 5px;\n"
"}")
        self.specter_center_x_field.setObjectName("specter_center_x_field")
        self.specter_center_y_field = QtWidgets.QLineEdit(parent=self.specter_frame)
        self.specter_center_y_field.setGeometry(QtCore.QRect(50, 180, 551, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.specter_center_y_field.setFont(font)
        self.specter_center_y_field.setStyleSheet("QLineEdit\n"
"{\n"
"    border-radius: 5px;\n"
"}")
        self.specter_center_y_field.setObjectName("specter_center_y_field")
        self.specter_radius_field = QtWidgets.QLineEdit(parent=self.specter_frame)
        self.specter_radius_field.setGeometry(QtCore.QRect(50, 260, 551, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.specter_radius_field.setFont(font)
        self.specter_radius_field.setStyleSheet("QLineEdit\n"
"{\n"
"    border-radius: 5px;\n"
"}")
        self.specter_radius_field.setObjectName("specter_radius_field")
        self.label_6 = QtWidgets.QLabel(parent=self.specter_frame)
        self.label_6.setGeometry(QtCore.QRect(220, 220, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_15 = QtWidgets.QLabel(parent=self.specter_frame)
        self.label_15.setGeometry(QtCore.QRect(16, 300, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.specter_angle_field = QtWidgets.QLineEdit(parent=self.specter_frame)
        self.specter_angle_field.setGeometry(QtCore.QRect(200, 300, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.specter_angle_field.setFont(font)
        self.specter_angle_field.setStyleSheet("QLineEdit\n"
"{\n"
"    border-radius: 5px;\n"
"}")
        self.specter_angle_field.setObjectName("specter_angle_field")
        self.specter_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.specter_label.setGeometry(QtCore.QRect(2080, 630, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.specter_label.setFont(font)
        self.specter_label.setWhatsThis("")
        self.specter_label.setStyleSheet("QLabel\n"
"{\n"
"    color: rgb(112, 146, 190);\n"
"}")
        self.specter_label.setObjectName("specter_label")
        self.pixmap_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.pixmap_label.setGeometry(QtCore.QRect(20, 20, 1800, 1350))
        self.pixmap_label.setMinimumSize(QtCore.QSize(1800, 1350))
        self.pixmap_label.setMaximumSize(QtCore.QSize(1800, 1350))
        self.pixmap_label.setStyleSheet("")
        self.pixmap_label.setText("")
        self.pixmap_label.setObjectName("pixmap_label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "computer graphic lab_03"))
        self.cda_button.setText(_translate("MainWindow", "ЦДА"))
        self.bresenham_float_button.setText(_translate("MainWindow", "Алгоритм Брезенхема вещественный"))
        self.bresenham_int_button.setText(_translate("MainWindow", "Алгоритм Брезенхема целочисленный"))
        self.bresenham_without_gradation_button.setText(_translate("MainWindow", "Алгоритм Брезенхема с устранением\n"
"ступенчатости"))
        self.vu_button.setText(_translate("MainWindow", "Алгоритм Ву"))
        self.library_function_button.setText(_translate("MainWindow", "Библиотечная функция"))
        self.gradation_measurement_button.setText(_translate("MainWindow", "Замеры ступенчатости"))
        self.time_measurement_button.setText(_translate("MainWindow", "Замеры времени"))
        self.algorithms_label.setText(_translate("MainWindow", "Алгоритм"))
        self.line_label.setText(_translate("MainWindow", "Отрезок"))
        self.measurements_label.setText(_translate("MainWindow", "Замеры"))
        self.screen_label.setText(_translate("MainWindow", "Экран"))
        self.label_1.setText(_translate("MainWindow", "Цвет фона"))
        self.clear_screen_button.setText(_translate("MainWindow", "Очистить экран"))
        self.label_16.setText(_translate("MainWindow", "Размер экрана:"))
        self.label_17.setText(_translate("MainWindow", "1800 x 1350"))
        self.draw_line_button.setText(_translate("MainWindow", "Построить прямую"))
        self.label_11.setText(_translate("MainWindow", "Y:"))
        self.label_10.setText(_translate("MainWindow", "X:"))
        self.label_9.setText(_translate("MainWindow", "Начальная точка"))
        self.label_14.setText(_translate("MainWindow", "Y:"))
        self.label_13.setText(_translate("MainWindow", "X:"))
        self.label_8.setText(_translate("MainWindow", "Цвет отрезка"))
        self.line_mode_button.setText(_translate("MainWindow", "Отрезок"))
        self.specter_mode_button.setText(_translate("MainWindow", "Спектр"))
        self.label_12.setText(_translate("MainWindow", "Конечная точка"))
        self.draw_specter_button.setText(_translate("MainWindow", "Построить спектр"))
        self.label_5.setText(_translate("MainWindow", "Y:"))
        self.label_4.setText(_translate("MainWindow", "X:"))
        self.label_3.setText(_translate("MainWindow", "Центр спектра"))
        self.label_7.setText(_translate("MainWindow", "R:"))
        self.label_2.setText(_translate("MainWindow", "Цвет отрезка"))
        self.label_6.setText(_translate("MainWindow", "Радиус спектра"))
        self.label_15.setText(_translate("MainWindow", "Угол спектра:"))
        self.specter_label.setText(_translate("MainWindow", "Спектр"))
