# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from config import border_color_1, border_color_2


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1248, 750)
        MainWindow.setMinimumSize(QtCore.QSize(1245, 750))
        MainWindow.setMaximumSize(QtCore.QSize(1250, 750))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.table_1 = QtWidgets.QTableWidget(self.centralwidget)
        self.table_1.setGeometry(QtCore.QRect(10, 170, 241, 541))
        self.table_1.setStyleSheet("QTableWidget\n"
"{\n"
"    border-radius: 7px;\n"
f"    border: 3px solid rgb{border_color_1};\n"
"}")
        self.table_1.setObjectName("table_1")
        self.table_1.setColumnCount(0)
        self.table_1.setRowCount(0)
        self.set_button_1 = QtWidgets.QRadioButton(self.centralwidget)
        self.set_button_1.setGeometry(QtCore.QRect(40, 140, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.set_button_1.setFont(font)
        self.set_button_1.setObjectName("set_button_1")
        self.table_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.table_2.setGeometry(QtCore.QRect(270, 170, 241, 541))
        self.table_2.setStyleSheet("QTableWidget\n"
"{\n"
"    border-radius: 7px;\n"
f"    border: 3px solid rgb{border_color_2};\n"
"}")
        self.table_2.setObjectName("table_2")
        self.table_2.setColumnCount(0)
        self.table_2.setRowCount(0)
        self.set_button_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.set_button_2.setGeometry(QtCore.QRect(300, 140, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.set_button_2.setFont(font)
        self.set_button_2.setObjectName("set_button_2")
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setGeometry(QtCore.QRect(160, 70, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.add_button.setFont(font)
        self.add_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(146, 164, 175);\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(115, 138, 153);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(115, 138, 153);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.add_button.setObjectName("add_button")
        self.del_button = QtWidgets.QPushButton(self.centralwidget)
        self.del_button.setGeometry(QtCore.QRect(10, 10, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.del_button.setFont(font)
        self.del_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(146, 164, 175);\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(115, 138, 153);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(115, 138, 153);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.del_button.setObjectName("del_button")
        self.del_all_button = QtWidgets.QPushButton(self.centralwidget)
        self.del_all_button.setGeometry(QtCore.QRect(10, 70, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.del_all_button.setFont(font)
        self.del_all_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(146, 164, 175);\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(115, 138, 153);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(115, 138, 153);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.del_all_button.setObjectName("del_all_button")
        self.calc_button = QtWidgets.QPushButton(self.centralwidget)
        self.calc_button.setGeometry(QtCore.QRect(160, 10, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.calc_button.setFont(font)
        self.calc_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(102, 208, 139);\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(54, 180, 97);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(54, 180, 97);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.calc_button.setObjectName("calc_button")

        self.cords_visibility_check = QtWidgets.QCheckBox(self.centralwidget)
        self.cords_visibility_check.setGeometry(QtCore.QRect(330, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        self.cords_visibility_check.setFont(font)
        self.cords_visibility_check.setObjectName("cords_visibility_check")
        self.axes_visibility_check = QtWidgets.QCheckBox(self.centralwidget)
        self.axes_visibility_check.setGeometry(QtCore.QRect(330, 10, 131, 21))
        self.axes_visibility_check.setFont(font)
        self.axes_visibility_check.setObjectName("axes_visibility_check")

        self.graphics_widget = QtWidgets.QWidget(self.centralwidget)
        self.graphics_widget.setGeometry(QtCore.QRect(530, 2, 701, 717))
        self.graphics_widget.setObjectName("graphics_widget")
        
        self.clear_button = QtWidgets.QPushButton(self.centralwidget)
        self.clear_button.setGeometry(QtCore.QRect(320, 70, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.clear_button.setFont(font)
        self.clear_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(146, 164, 175);\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(115, 138, 153);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(115, 138, 153);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.clear_button.setObjectName("clear_button")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "computer graphic lab_01"))
        self.set_button_1.setText(_translate("MainWindow", "Множество №1"))
        self.set_button_2.setText(_translate("MainWindow", "Множество №2"))
        self.add_button.setText(_translate("MainWindow", "Добавить"))
        self.del_button.setText(_translate("MainWindow", "Удалить"))
        self.del_all_button.setText(_translate("MainWindow", "Удалить все"))
        self.calc_button.setText(_translate("MainWindow", "Calculate"))
        self.cords_visibility_check.setText(_translate("MainWindow", "show cords"))
        self.axes_visibility_check.setText(_translate("MainWindow", "show axes"))
        self.clear_button.setText(_translate("MainWindow", "Очистить"))
