# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files\point_add_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(260, 170)
        Dialog.setMinimumSize(QtCore.QSize(260, 170))
        Dialog.setMaximumSize(QtCore.QSize(260, 170))
        self.button_box = QtWidgets.QDialogButtonBox(Dialog)
        self.button_box.setGeometry(QtCore.QRect(30, 110, 191, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.y_label = QtWidgets.QLabel(Dialog)
        self.y_label.setGeometry(QtCore.QRect(40, 60, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(10)
        self.y_label.setFont(font)
        self.y_label.setObjectName("y_label")
        self.x_label = QtWidgets.QLabel(Dialog)
        self.x_label.setGeometry(QtCore.QRect(40, 30, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(10)
        self.x_label.setFont(font)
        self.x_label.setObjectName("x_label")
        self.x_input_line = QtWidgets.QLineEdit(Dialog)
        self.x_input_line.setGeometry(QtCore.QRect(70, 30, 131, 22))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.x_input_line.setFont(font)
        self.x_input_line.setText("")
        self.x_input_line.setObjectName("x_input_line")
        self.y_input_line = QtWidgets.QLineEdit(Dialog)
        self.y_input_line.setGeometry(QtCore.QRect(70, 60, 131, 22))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.y_input_line.setFont(font)
        self.y_input_line.setObjectName("y_input_line")

        self.retranslateUi(Dialog)
        self.button_box.accepted.connect(Dialog.accept) # type: ignore
        self.button_box.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Добавление точки"))
        self.y_label.setText(_translate("Dialog", "Y:"))
        self.x_label.setText(_translate("Dialog", "X:"))
